### ISSUE TITLE
Consider enabling CKAN support in SpaceDock

### ISSUE THREAD

**Issue by kupiakos** [ColinZeidler/KSP2-HideDistantOrbits#4]
According to the [CKAN docs](https://github.com/KSP-CKAN/CKAN/wiki/How-does-CKAN-work#pull-requests), there's a checkbox you can click in SpaceDock to automatically register the mod with their system. Alternatively the mod can be added manually.

CKAN is great! :)

**Comment by ColinZeidler** [comment]
I've enabled it now through spacedock. not very familiar with how CKAN works, so hopefully if there are any issues people can raise them in here.
